PERIOD_MAP = {
    "period": "period",
    "date": "period",
    "year": "period",
    "period ending": "period",
    "fiscal year": "period",
    "fiscal period": "period",
    "reporting period": "period",
    "year ended": "period",
    "years ended": "period",
    "quarter ended": "period",
    "quarters ended": "period",
    "as of": "period",
    "balance sheet date": "period",
    "fy period": "period",
}

INCOME_MAP = {
    # revenue
    "revenue": "revenue",
    "revenues": "revenue",
    "total revenue": "revenue",
    "sales": "revenue",
    "net sales": "revenue",
    "total net sales": "revenue",
    "net revenues": "revenue",
    "total net revenues": "revenue",
    # cogs
    "cost of sales": "cogs",
    "total cost of sales": "cogs",
    "cost of revenue": "cogs",
    "cost of revenues": "cogs",
    "cost of goods sold": "cogs",
    "cost of products sold": "cogs",
    # gross profit
    "gross profit": "gross_profit",
    # operating expenses
    "operating expense": "operating_expenses",
    "operating expenses": "operating_expenses",
    "total operating expenses": "operating_expenses",
    # ebit
    "ebit": "ebit",
    "earnings before interest and taxes": "ebit",
    "earnings before interest and tax": "ebit",
    "operating income": "ebit",
    "operating income loss": "ebit",
    "income from operations": "ebit",
    "operating profit": "ebit",
    # depreciation - standalone only
    "depreciation": "depreciation",
    "depreciation expense": "depreciation",
    # amortization - standalone only
    "amortization": "amortization",
    "amortisation": "amortization",
    "amortization expense": "amortization",
    "amortisation expense": "amortization",
    # ebitda
    "ebitda": "ebitda",
    "earnings before interest taxes depreciation and amortization": "ebitda",
    "earnings before interest taxes depreciation and amortisation": "ebitda",
    "earnings before interest and taxes depreciation and amortization": "ebitda",
    "earnings before interest and taxes depreciation and amortisation": "ebitda",
    # net income
    "net income": "net_income",
    "net income loss": "net_income",
    "profit": "net_income",
    "profit for the year": "net_income",
    "profit for the period": "net_income",
}

BALANCE_MAP = {
    # cash
    "cash and cash equivalents": "cash_and_equivalents",
    "cash and equivalents": "cash_and_equivalents",
    # receivables
    "accounts receivable": "accounts_receivable",
    "accounts receivable net": "accounts_receivable",
    "accounts receivable net of allowance": "accounts_receivable",
    "accounts receivable net of allowances": "accounts_receivable",
    "trade receivables": "accounts_receivable",
    # inventory
    "inventory": "inventory",
    "inventories": "inventory",
    # assets
    "current assets": "current_assets",
    "total current assets": "current_assets",
    "total assets": "total_assets",
    # payables and liabilities
    "accounts payable": "accounts_payable",
    "trade payables": "accounts_payable",
    "current liabilities": "current_liabilities",
    "total current liabilities": "current_liabilities",
    "total liabilities": "total_liabilities",
    "total liabilities net minority interest": "total_liabilities",
    # equity
    "shareholders equity": "total_equity",
    "stockholders equity": "total_equity",
    "total shareholders equity": "total_equity",
    "total stockholders equity": "total_equity",
    "total equity": "total_equity",
    "total equity gross minority interest": "total_equity",
}

CASHFLOW_MAP = {
    # operating cash flow
    "operating cash flow": "operating_cash_flow",
    "cash flow from operations": "operating_cash_flow",
    "net cash provided by operating activities": "operating_cash_flow",
    "net cash from operating activities": "operating_cash_flow",
    "cash provided by operating activities": "operating_cash_flow",
    "cash generated by operating activities": "operating_cash_flow",
    # capex
    "capital expenditure": "capital_expenditures",
    "capital expenditures": "capital_expenditures",
    "capital additions net": "capital_expenditures",
    "purchase of property plant and equipment": "capital_expenditures",
    "purchase of property and equipment": "capital_expenditures",
    "purchases of property and equipment": "capital_expenditures",
    "payments for acquisition of property plant and equipment": "capital_expenditures",
    "purchases of fixed assets": "capital_expenditures",
    "purchases of property and equipment net of proceeds from sales and incentives": (
        "capital_expenditures"
    ),
    # free cash flow
    "free cash flow": "free_cash_flow",
    "free cash flows": "free_cash_flow",
}

# These labels are intentionally preserved for user review because automatic
# mapping could be misleading.
REVIEW_ONLY_LABELS = {
    "depreciation and amortization",
    "depreciation and amortization expenses",
    "depreciation and amortisation",
    "depreciation and amortisation expenses",
    "gross margin",
    "gross margin %",
    "receivables",
    "cash on hand",
    "accounts payable and accrued expenses",
    "adjusted ebitda",
    "adjusted free cash flow",
}

NUMERIC_COLUMNS = {
    "revenue",
    "cogs",
    "gross_profit",
    "operating_expenses",
    "ebit",
    "depreciation",
    "amortization",
    "ebitda",
    "net_income",
    "cash_and_equivalents",
    "accounts_receivable",
    "inventory",
    "current_assets",
    "total_assets",
    "accounts_payable",
    "current_liabilities",
    "total_liabilities",
    "total_equity",
    "operating_cash_flow",
    "capital_expenditures",
    "free_cash_flow",
}

REVIEW_NUMERIC_COLUMNS = {
    "depreciation and amortization",
    "depreciation and amortization expenses",
    "depreciation and amortisation",
    "depreciation and amortisation expenses",
}

POSITIVE_MAGNITUDE_COLUMNS = {
    "cogs",
    "operating_expenses",
    "depreciation",
    "amortization",
    "capital_expenditures",
}


def get_mapping_for_statement(statement_type):
    """Return the conservative mapping for one statement type."""
    normalized_statement_type = str(statement_type).lower()

    if "income" in normalized_statement_type:
        return {**PERIOD_MAP, **INCOME_MAP}
    if "balance" in normalized_statement_type:
        return {**PERIOD_MAP, **BALANCE_MAP}
    if (
        "cashflow" in normalized_statement_type
        or "cash flow" in normalized_statement_type
    ):
        return {**PERIOD_MAP, **CASHFLOW_MAP}

    return PERIOD_MAP


def map_column_name(normalized_name, statement_type):
    """Map a normalized label when safe; otherwise leave it available for review."""
    if normalized_name in REVIEW_ONLY_LABELS:
        return normalized_name

    mapping = get_mapping_for_statement(statement_type)
    return mapping.get(normalized_name, normalized_name)
